# catalog.py

PISTOLS = {
    "Semi-Auto": [
        {"name": "Glock 17", "caliber": "9×19mm", "price": "$500–$650", "manufacturer": "Glock", "image": "https://en.wikipedia.org/wiki/File:Glock_17_(6825676904)_%D0%B1%D0%B5%D0%B7_%D1%84%D0%BE%D0%BD%D0%B0.jpg"},
        {"name": "Glock 19", "caliber": "9×19mm", "price": "$500–$650", "manufacturer": "Glock", "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Glock_19_%289mm%29%2C_Generation_3.jpg/250px-Glock_19_%289mm%29%2C_Generation_3.jpg"},
        {"name": "Glock 26", "caliber": "9×19mm", "price": "$500–$650", "manufacturer": "Glock", "image": "https://en.wikipedia.org/wiki/File:Glock_26_(6971790359).jpg"},
        {"name": "Glock 34", "caliber": "9×19mm", "price": "$600–$750", "manufacturer": "Glock", "image": ""},
        {"name": "Glock 43", "caliber": "9×19mm", "price": "$450–$600", "manufacturer": "Glock", "image": ""},
        {"name": "Glock 21", "caliber": ".45 ACP", "price": "$550–$700", "manufacturer": "Glock", "image": ""},
        {"name": "SIG Sauer P320", "caliber": "9mm", "price": "$500–$700", "manufacturer": "SIG Sauer", "image": "https://en.wikipedia.org/wiki/File:Sig_Sauer_P320_Modular_Handgun_System.jpg"},
        {"name": "SIG Sauer P365", "caliber": "9mm", "price": "$500–$650", "manufacturer": "SIG Sauer", "image": "https://en.wikipedia.org/wiki/File:SIG_Sauer_P365_left_side.jpg"},
        {"name": "SIG Sauer P226", "caliber": "9mm", "price": "$700–$900", "manufacturer": "SIG Sauer", "image": "https://en.wikipedia.org/wiki/File:SIG_Sauer_P226_neu.jpg"},
        {"name": "SIG Sauer P229", "caliber": "9mm", "price": "$700–$900", "manufacturer": "SIG Sauer", "image": ""},
        {"name": "Smith & Wesson M&P 9", "caliber": "9mm", "price": "$450–$600", "manufacturer": "Smith & Wesson", "image": ""},
        {"name": "Smith & Wesson Shield", "caliber": "9mm", "price": "$400–$550", "manufacturer": "Smith & Wesson", "image": ""},
        {"name": "Beretta 92FS", "caliber": "9mm", "price": "$600–$750", "manufacturer": "Beretta", "image": "https://en.wikipedia.org/wiki/File:Beretta-92FS.jpg"},
        {"name": "Beretta APX", "caliber": "9mm", "price": "$450–$600", "manufacturer": "Beretta", "image": ""},
        {"name": "Beretta PX4 Storm", "caliber": "9mm", "price": "$450–$600", "manufacturer": "Beretta", "image": "https://en.wikipedia.org/wiki/File:BerettaPX4Storm.jpg"},
        {"name": "CZ 75", "caliber": "9mm", "price": "$600–$800", "manufacturer": "CZ", "image": "https://en.wikipedia.org/wiki/File:CZ_75_short_rail_1975-79.png"},
        {"name": "CZ P-10 C", "caliber": "9mm", "price": "$450–$600", "manufacturer": "CZ", "image": "https://en.wikipedia.org/wiki/File:CZ_P-10_C_left.jpg"},
        {"name": "CZ Shadow 2", "caliber": "9mm", "price": "$1,100–$1,600", "manufacturer": "CZ", "image": ""},
        {"name": "Ruger SR9", "caliber": "9mm", "price": "$400–$550", "manufacturer": "Ruger", "image": "https://en.wikipedia.org/wiki/File:Ruger_SR9_(cropped).jpg"},
        {"name": "Ruger Security-9", "caliber": "9mm", "price": "$350–$500", "manufacturer": "Ruger", "image": "https://en.wikipedia.org/wiki/File:Ruger_Security-9_Left_View_(cropped_and_rotated).jpg"},
        {"name": "Ruger LCP", "caliber": ".380 ACP", "price": "$300–$450", "manufacturer": "Ruger", "image": "https://en.wikipedia.org/wiki/File:Ruger_LCP_380_Pistol.png"},
        {"name": "Colt 1911", "caliber": ".45 ACP", "price": "$800–$1,200", "manufacturer": "Colt", "image": "https://en.wikipedia.org/wiki/File:M1911_and_M1911A1_pistols.JPG"},
        {"name": "Kimber 1911", "caliber": ".45 ACP", "price": "$900–$1,400", "manufacturer": "Kimber", "image": ""},
        {"name": "Springfield XD", "caliber": "9mm", "price": "$450–$600", "manufacturer": "Springfield Armory", "image": "https://en.wikipedia.org/wiki/File:SAXD_.45_compact.png"},
        {"name": "Springfield Hellcat", "caliber": "9mm", "price": "$500–$650", "manufacturer": "Springfield Armory", "image": ""},
        {"name": "FN 509", "caliber": "9mm", "price": "$600–$750", "manufacturer": "FN", "image": "https://en.wikipedia.org/wiki/File:FN_509.jpg"},
        {"name": "FN FNX-45", "caliber": ".45 ACP", "price": "$700–$900", "manufacturer": "FN", "image": ""},
        {"name": "Walther PPQ", "caliber": "9mm", "price": "$500–$650", "manufacturer": "Walther", "image": "https://en.wikipedia.org/wiki/File:Walther_PPQ.jpg"},
        {"name": "Walther PDP", "caliber": "9mm", "price": "$550–$700", "manufacturer": "Walther", "image": "https://en.wikipedia.org/wiki/File:Walther_PDP_Compact_4%22.jpg"},
        {"name": "Walther PPK", "caliber": ".380 ACP", "price": "$600–$850", "manufacturer": "Walther", "image": ""},
        {"name": "Taurus G2C", "caliber": "9mm", "price": "$250–$350", "manufacturer": "Taurus", "image": ""},
        {"name": "Taurus PT92", "caliber": "9mm", "price": "$400–$550", "manufacturer": "Taurus", "image": "https://en.wikipedia.org/wiki/File:ARMS_%26_Hunting_2012_exhibition_(474-17).jpg"},
        {"name": "Canik TP9SF", "caliber": "9mm", "price": "$350–$500", "manufacturer": "Canik", "image": ""},
        {"name": "Canik Mete SFx", "caliber": "9mm", "price": "$500–$650", "manufacturer": "Canik", "image": ""},
    ],

    "Automatic": [
        {"name": "Glock 18", "caliber": "9×19mm", "price": "Restricted", "manufacturer": "Glock", "image": ""},
        {"name": "Glock 18C", "caliber": "9×19mm", "price": "Restricted", "manufacturer": "Glock", "image": ""},
        {"name": "Beretta 93R", "caliber": "9×19mm", "price": "Restricted", "manufacturer": "Beretta", "image": "https://en.wikipedia.org/wiki/File:B93R_(2).jpg"},
        {"name": "Stechkin APS", "caliber": "9×18mm", "price": "Restricted", "manufacturer": "Tula Arsenal", "image": ""},
        {"name": "CZ 75 Automatic", "caliber": "9×19mm", "price": "Restricted", "manufacturer": "CZ", "image": ""},
    ],

    "Revolver": [
        {"name": "Smith & Wesson Model 686", "caliber": ".357 Magnum", "price": "$700–$900", "manufacturer": "Smith & Wesson", "image": "https://en.wikipedia.org/wiki/File:Flickr_-_~Steve_Z~_-_S%5EW_686-_2.jpg"},
        {"name": "Smith & Wesson Model 29", "caliber": ".44 Magnum", "price": "$900–$1,200", "manufacturer": "Smith & Wesson", "image": "https://en.wikipedia.org/wiki/File:Smith_%26_Wesson_Model_29_retouched.jpg"},
        {"name": "Smith & Wesson Model 642", "caliber": ".38 Special", "price": "$400–$600", "manufacturer": "Smith & Wesson", "image": "https://en.wikipedia.org/wiki/File:S%26W642.jpg"},
        {"name": "Colt Python", "caliber": ".357 Magnum", "price": "$1,200–$1,800", "manufacturer": "Colt", "image": "https://en.wikipedia.org/wiki/File:Colt-Python.jpg"},
        {"name": "Ruger GP100", "caliber": ".357 Magnum", "price": "$650–$850", "manufacturer": "Ruger", "image": "https://en.wikipedia.org/wiki/File:Ruger_GP100_.357_Stainless.jpg"},
        {"name": "Ruger Redhawk", "caliber": ".44 Magnum", "price": "$800–$1,100", "manufacturer": "Ruger", "image": ""},
        {"name": "Taurus Judge", "caliber": ".410 / .45 Colt", "price": "$450–$650", "manufacturer": "Taurus", "image": "https://en.wikipedia.org/wiki/File:RagingJudgeMagnum.jpg"},
        {"name": "Taurus Tracker", "caliber": ".357 Magnum", "price": "$400–$600", "manufacturer": "Taurus", "image": ""},
        {"name": "Colt King Cobra", "caliber": ".357 Magnum", "price": "$900–$1,200", "manufacturer": "Colt", "image": "https://en.wikipedia.org/wiki/File:Colt-KC-357.jpg"},
        {"name": "Ruger SP101", "caliber": ".357 Magnum", "price": "$600–$800", "manufacturer": "Ruger", "image": "https://en.wikipedia.org/wiki/File:Sp101corbon.JPG"},
        {"name": "Smith & Wesson Model 60", "caliber": ".357 Magnum", "price": "$650–$850", "manufacturer": "Smith & Wesson", "image": "https://en.wikipedia.org/wiki/File:S%26W_60_3in.jpg"},
        {"name": "Smith & Wesson Model 19", "caliber": ".357 Magnum", "price": "$750–$950", "manufacturer": "Smith & Wesson", "image": "https://en.wikipedia.org/wiki/File:Smith_Model_19_.357_Magnum.jpg"},
        {"name": "Charter Arms Bulldog", "caliber": ".44 Special", "price": "$400–$550", "manufacturer": "Charter Arms", "image": "https://en.wikipedia.org/wiki/File:Charter_Arms_Bulldog_2.JPG"},
        {"name": "Ruger LCR", "caliber": ".38 Special", "price": "$450–$600", "manufacturer": "Ruger", "image": "https://en.wikipedia.org/wiki/File:Ruger-LCR-38-sp-front-quarter.jpg"},
        {"name": "Colt Anaconda", "caliber": ".44 Magnum", "price": "$1,300–$1,700", "manufacturer": "Colt", "image": "https://en.wikipedia.org/wiki/File:Colt_Anacondas_in_3_barrel_lengths.jpg"},
    ]
}

RIFLES = {
    "Semi-Auto": [
        {"name": "AR-15", "caliber": "5.56×45mm", "price": "$500–$1,000", "manufacturer": "Various", "image": "https://en.wikipedia.org/wiki/File:Stag2wi_.jpg"},
        {"name": "AR-10", "caliber": ".308 Win", "price": "$900–$1,500", "manufacturer": "Various", "image": "https://en.wikipedia.org/wiki/File:AR10_Armalite_vue_d%27ensemble_noBG.png"},
        {"name": "PSA AR-15", "caliber": "5.56×45mm", "price": "$450–$750", "manufacturer": "PSA", "image": ""},
        {"name": "Colt AR15", "caliber": "5.56×45mm", "price": "$900–$1,300", "manufacturer": "Colt", "image": ""},
        {"name": "Daniel Defense DDM4", "caliber": "5.56×45mm", "price": "$1,400–$2,000", "manufacturer": "Daniel Defense", "image": ""},
        {"name": "SIG Sauer MCX", "caliber": "5.56×45mm", "price": "$1,600–$2,500", "manufacturer": "SIG Sauer", "image": "https://en.wikipedia.org/wiki/File:SIG-MCX-Rifle.jpeg"},
        {"name": "FN SCAR 16", "caliber": "5.56×45mm", "price": "$2,500–$3,200", "manufacturer": "FN", "image": ""},
        {"name": "AK-47", "caliber": "7.62×39mm", "price": "$600–$1,200", "manufacturer": "Various", "image": "https://en.wikipedia.org/wiki/File:AK-47_type_II_noBG.png"},
        {"name": "AK-74", "caliber": "5.45×39mm", "price": "$700–$1,300", "manufacturer": "Various", "image": "https://en.wikipedia.org/wiki/File:Ak74l.png"},
        {"name": "Zastava ZPAP M70", "caliber": "7.62×39mm", "price": "$900–$1,300", "manufacturer": "Zastava", "image": ""},
        {"name": "WASR-10", "caliber": "7.62×39mm", "price": "$700–$1,000", "manufacturer": "Century Arms", "image": "https://en.wikipedia.org/wiki/File:Wasr-10.jpg"},
        {"name": "Ruger Mini-14", "caliber": "5.56×45mm", "price": "$900–$1,200", "manufacturer": "Ruger", "image": "https://en.wikipedia.org/wiki/File:Mini14GB_noBG.jpg"},
        {"name": "Ruger 10/22", "caliber": ".22 LR", "price": "$250–$400", "manufacturer": "Ruger", "image": "https://en.wikipedia.org/wiki/File:Ruger_10-22.jpg"},
        {"name": "Springfield M1A", "caliber": ".308 Win", "price": "$1,400–$2,000", "manufacturer": "Springfield Armory", "image": "https://en.wikipedia.org/wiki/File:M1A_Kafziel.jpg"},
        {"name": "IWI Tavor X95", "caliber": "5.56×45mm", "price": "$1,500–$2,000", "manufacturer": "IWI", "image": "https://en.wikipedia.org/wiki/File:MicroTavorX95MARS-white.jpg"},
        {"name": "Steyr AUG", "caliber": "5.56×45mm", "price": "$1,800–$2,300", "manufacturer": "Steyr", "image": "https://en.wikipedia.org/wiki/File:AUG_A1_508mm_04.jpg"},
        {"name": "FN PS90", "caliber": "5.7×28mm", "price": "$1,500–$1,900", "manufacturer": "FN", "image": "https://en.wikipedia.org/wiki/File:FN_P90_LV_Submachine_Gun_with_Tri_Rail_Left.jpg"},
        {"name": "Kel-Tec SUB-2000", "caliber": "9mm", "price": "$450–$650", "manufacturer": "Kel-Tec", "image": "https://en.wikipedia.org/wiki/File:Kel_Tec_Sub-2000_(41525896831).jpg"},
        {"name": "Kel-Tec RDB", "caliber": "5.56×45mm", "price": "$900–$1,200", "manufacturer": "Kel-Tec", "image": "https://en.wikipedia.org/wiki/File:Rdb_side.jpg"},
        {"name": "Hi-Point 995TS", "caliber": "9mm", "price": "$300–$450", "manufacturer": "Hi-Point", "image": ""},
    ],

    "Automatic": [
        {"name": "M16A4", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "Colt", "image": "https://en.wikipedia.org/wiki/File:M16A4-JH01_noBG.jpg"},
        {"name": "M4 Carbine", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "Colt", "image": "https://en.wikipedia.org/wiki/File:PEO_M4_Carbine_RAS_M68_CCO.png"},
        {"name": "AKM", "caliber": "7.62×39mm", "price": "Restricted", "manufacturer": "Kalashnikov Concern", "image": "https://en.wikipedia.org/wiki/File:AKM_automatkarbin_Ryssland_-_7,62x39mm_-_Arm%C3%A9museum_bothsides_noBG.png"},
        {"name": "AK-74M", "caliber": "5.45×39mm", "price": "Restricted", "manufacturer": "Kalashnikov Concern", "image": "https://en.wikipedia.org/wiki/File:Ak-74mpdomain.JPG"},
        {"name": "HK416", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "Heckler & Koch", "image": "https://en.wikipedia.org/wiki/File:HK416N.png"},
        {"name": "SIG SG 550", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "SIG", "image": "https://en.wikipedia.org/wiki/File:Stgw_90.jpg"},
        {"name": "FAMAS F1", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "GIAT", "image": "https://en.wikipedia.org/wiki/File:Rifles_FAMAS.jpg"},
        {"name": "Steyr AUG A1 (Auto)", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "Steyr", "image": ""},
    ],

    "Bolt-Action": [
        {"name": "Remington 700", "caliber": ".308 Win", "price": "$600–$900", "manufacturer": "Remington", "image": "https://en.wikipedia.org/wiki/File:Remington_Model_700.JPG"},
        {"name": "Savage 110", "caliber": ".308 Win", "price": "$600–$900", "manufacturer": "Savage", "image": ""},
        {"name": "Savage Axis", "caliber": ".308 Win", "price": "$350–$550", "manufacturer": "Savage", "image": ""},
        {"name": "Ruger American", "caliber": ".308 Win", "price": "$400–$650", "manufacturer": "Ruger", "image": "https://en.wikipedia.org/wiki/File:Ruger-American-Rifle.jpg"},
        {"name": "Ruger Precision Rifle", "caliber": ".308 Win", "price": "$1,300–$1,800", "manufacturer": "Ruger", "image": "https://en.wikipedia.org/wiki/File:Ruger_Precision_Rifle_308_Gen_1.jpg"},
        {"name": "Tikka T3x", "caliber": ".308 Win", "price": "$700–$1,000", "manufacturer": "Tikka", "image": ""},
        {"name": "Bergara B-14", "caliber": ".308 Win", "price": "$700–$1,000", "manufacturer": "Bergara", "image": ""},
        {"name": "Howa 1500", "caliber": ".308 Win", "price": "$500–$750", "manufacturer": "Howa", "image": ""},
        {"name": "Weatherby Vanguard", "caliber": ".308 Win", "price": "$550–$800", "manufacturer": "Weatherby", "image": ""},
        {"name": "Winchester Model 70", "caliber": ".30-06", "price": "$800–$1,300", "manufacturer": "Winchester", "image": "https://en.wikipedia.org/wiki/File:Winchestermodel70.jpg"},
        {"name": "Winchester XPR", "caliber": ".308 Win", "price": "$450–$650", "manufacturer": "Winchester", "image": ""},
        {"name": "Christensen Arms Mesa", "caliber": ".308 Win", "price": "$1,200–$1,700", "manufacturer": "Christensen Arms", "image": ""},
        {"name": "Mossberg Patriot", "caliber": ".308 Win", "price": "$400–$600", "manufacturer": "Mossberg", "image": ""},
        {"name": "CZ 457", "caliber": ".22 LR", "price": "$450–$700", "manufacturer": "CZ", "image": "https://en.wikipedia.org/wiki/File:CZ_457_Lux.jpg"},
        {"name": "Barrett MRAD", "caliber": ".308 Win", "price": "$4,000–$6,000", "manufacturer": "Barrett", "image": "https://en.wikipedia.org/wiki/File:Barrett-MRAD-sniper-rifle-01.png"},
        {"name": "Browning X-Bolt", "caliber": ".308 Win", "price": "$700–$1,200", "manufacturer": "Browning", "image": "https://en.wikipedia.org/wiki/File:Browning_X_Bolt.png"},
        {"name": "Savage 12 FV", "caliber": ".308 Win", "price": "$600–$900", "manufacturer": "Savage", "image": ""},
        {"name": "Ruger Hawkeye", "caliber": ".308 Win", "price": "$700–$1,000", "manufacturer": "Ruger", "image": "https://en.wikipedia.org/wiki/File:Flickr_-_~Steve_Z~_-_Ruger_Hawkeye_(7).jpg"},
        {"name": "T/C Compass", "caliber": ".308 Win", "price": "$350–$500", "manufacturer": "Thompson/Center", "image": ""},
        {"name": "Bergara Premier", "caliber": ".308 Win", "price": "$2,000–$3,000", "manufacturer": "Bergara", "image": ""},
    ],

    "Lever-Action": [
        {"name": "Marlin 336", "caliber": ".30-30", "price": "$600–$900", "manufacturer": "Marlin", "image": "https://en.wikipedia.org/wiki/File:Marlin_336W.png"},
        {"name": "Marlin 1895", "caliber": ".45-70 Gov", "price": "$900–$1,300", "manufacturer": "Marlin", "image": ""},
        {"name": "Henry Big Boy", "caliber": ".357 Magnum", "price": "$700–$1,000", "manufacturer": "Henry", "image": ""},
        {"name": "Henry Long Ranger", "caliber": ".308 Win", "price": "$900–$1,200", "manufacturer": "Henry", "image": ""},
        {"name": "Henry Golden Boy", "caliber": ".22 LR", "price": "$500–$750", "manufacturer": "Henry", "image": ""},
        {"name": "Winchester 1894", "caliber": ".30-30", "price": "$800–$1,200", "manufacturer": "Winchester", "image": "https://en.wikipedia.org/wiki/File:Winchester-94-32spl_noBG.png"},
        {"name": "Rossi R92", "caliber": ".357 Magnum", "price": "$550–$750", "manufacturer": "Rossi", "image": ""},
        {"name": "Browning BLR", "caliber": ".308 Win", "price": "$800–$1,200", "manufacturer": "Browning", "image": "https://en.wikipedia.org/wiki/File:Browning_BLR.jpg"},
        {"name": "Marlin 39A", "caliber": ".22 LR", "price": "$700–$1,000", "manufacturer": "Marlin", "image": "https://en.wikipedia.org/wiki/File:Marlin_39A.jpg"},
        {"name": "Henry Side Gate", "caliber": ".45-70 Gov", "price": "$900–$1,300", "manufacturer": "Henry", "image": ""},
    ],
}


SHOTGUNS = {
    "Pump-Action": [
        {"name": "Remington 870", "caliber": "12 Gauge", "price": "$350–$500", "manufacturer": "Remington", "image": "https://en.wikipedia.org/wiki/File:Remington_870_Fieldmaster.jpg"},
        {"name": "Mossberg 500", "caliber": "12 Gauge", "price": "$300–$450", "manufacturer": "Mossberg", "image": "https://en.wikipedia.org/wiki/File:PEO_Mossberg_590A1.jpg"},
        {"name": "Mossberg 590", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Mossberg", "image": "https://en.wikipedia.org/wiki/File:PEO_Mossberg_590A1.jpg"},
        {"name": "Mossberg Maverick 88", "caliber": "12 Gauge", "price": "$250–$350", "manufacturer": "Mossberg", "image": "https://en.wikipedia.org/wiki/File:Mossberg_Maverick_88.png"},
        {"name": "Winchester SXP", "caliber": "12 Gauge", "price": "$300–$450", "manufacturer": "Winchester", "image": ""},
        {"name": "Benelli Nova", "caliber": "12 Gauge", "price": "$400–$550", "manufacturer": "Benelli", "image": "https://en.wikipedia.org/wiki/File:Benelli_nova_camo.jpg"},
        {"name": "Benelli SuperNova", "caliber": "12 Gauge", "price": "$450–$600", "manufacturer": "Benelli", "image": "https://en.wikipedia.org/wiki/File:ARMS_%26_Hunting_2010_exhibition_(331-09).jpg"},
        {"name": "Stevens 320", "caliber": "12 Gauge", "price": "$250–$350", "manufacturer": "Stevens", "image": ""},
        {"name": "Browning BPS", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Browning", "image": ""},
        {"name": "Kel-Tec KSG", "caliber": "12 Gauge", "price": "$700–$900", "manufacturer": "Kel-Tec", "image": "https://en.wikipedia.org/wiki/File:Kel-tec_KSG1.jpg"},
        {"name": "TriStar Cobra", "caliber": "12 Gauge", "price": "$200–$300", "manufacturer": "TriStar", "image": ""},
        {"name": "Mossberg 835 Ulti-Mag", "caliber": "12 Gauge", "price": "$350–$500", "manufacturer": "Mossberg", "image": ""},
        {"name": "Winchester Model 12", "caliber": "12 Gauge", "price": "$600–$1,000", "manufacturer": "Winchester", "image": "https://en.wikipedia.org/wiki/File:Winchester_Model_1912.JPG"},
        {"name": "H&R Pardner Pump", "caliber": "12 Gauge", "price": "$250–$350", "manufacturer": "H&R", "image": ""},
        {"name": "Ithaca 37", "caliber": "12 Gauge", "price": "$600–$900", "manufacturer": "Ithaca", "image": "https://en.wikipedia.org/wiki/File:Ithaca_37.jpg"},
    ],

    "Semi-Auto": [
        {"name": "Remington 1100", "caliber": "12 Gauge", "price": "$600–$900", "manufacturer": "Remington", "image": "https://en.wikipedia.org/wiki/File:Remington_1100_Tactical_8_Rounds.jpg"},
        {"name": "Remington 1187", "caliber": "12 Gauge", "price": "$650–$950", "manufacturer": "Remington", "image": ""},
        {"name": "Mossberg 930", "caliber": "12 Gauge", "price": "$450–$650", "manufacturer": "Mossberg", "image": "https://en.wikipedia.org/wiki/File:Mossberg930_SPX.jpg"},
        {"name": "Mossberg 940 Pro", "caliber": "12 Gauge", "price": "$900–$1,200", "manufacturer": "Mossberg", "image": ""},
        {"name": "Benelli M2", "caliber": "12 Gauge", "price": "$1,100–$1,500", "manufacturer": "Benelli", "image": "https://en.wikipedia.org/wiki/File:Benelli_M2_Pro_Black_7%2B1.jpg"},
        {"name": "Benelli M4", "caliber": "12 Gauge", "price": "$1,800–$2,200", "manufacturer": "Benelli", "image": "https://en.wikipedia.org/wiki/File:Benelli_m4_2.jpg"},
        {"name": "Benelli Montefeltro", "caliber": "12 Gauge", "price": "$900–$1,200", "manufacturer": "Benelli", "image": ""},
        {"name": "Benelli Ethos", "caliber": "12 Gauge", "price": "$1,500–$2,000", "manufacturer": "Benelli", "image": ""},
        {"name": "Beretta A300", "caliber": "12 Gauge", "price": "$600–$800", "manufacturer": "Beretta", "image": ""},
        {"name": "Beretta 1301", "caliber": "12 Gauge", "price": "$1,000–$1,400", "manufacturer": "Beretta", "image": "https://en.wikipedia.org/wiki/File:Beretta_1301_Tactical.jpg"},
        {"name": "Beretta A400", "caliber": "12 Gauge", "price": "$1,300–$1,800", "manufacturer": "Beretta", "image": ""},
        {"name": "Browning A5", "caliber": "12 Gauge", "price": "$1,200–$1,800", "manufacturer": "Browning", "image": ""},
        {"name": "Browning Maxus", "caliber": "12 Gauge", "price": "$900–$1,200", "manufacturer": "Browning", "image": ""},
        {"name": "Stoeger M3000", "caliber": "12 Gauge", "price": "$350–$500", "manufacturer": "Stoeger", "image": ""},
        {"name": "Weatherby Element", "caliber": "12 Gauge", "price": "$350–$550", "manufacturer": "Weatherby", "image": ""},
    ],

    "Over/Under": [
        {"name": "CZ Drake", "caliber": "12 Gauge", "price": "$600–$800", "manufacturer": "CZ", "image": ""},
        {"name": "CZ Redhead", "caliber": "12 Gauge", "price": "$700–$900", "manufacturer": "CZ", "image": ""},
        {"name": "Browning Citori", "caliber": "12 Gauge", "price": "$1,500–$2,500", "manufacturer": "Browning", "image": "https://en.wikipedia.org/wiki/File:Bockdoppelflinte_JB.jpg"},
        {"name": "Winchester 101", "caliber": "12 Gauge", "price": "$1,200–$1,800", "manufacturer": "Winchester", "image": ""},
        {"name": "Stoeger Condor", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Stoeger", "image": ""},
        {"name": "Mossberg Silver Reserve", "caliber": "12 Gauge", "price": "$500–$700", "manufacturer": "Mossberg", "image": ""},
        {"name": "Stevens 555", "caliber": "12 Gauge", "price": "$450–$650", "manufacturer": "Stevens", "image": ""},
        {"name": "Franchi Instinct", "caliber": "12 Gauge", "price": "$600–$850", "manufacturer": "Franchi", "image": ""},
        {"name": "Weatherby Orion", "caliber": "12 Gauge", "price": "$650–$900", "manufacturer": "Weatherby", "image": ""},
        {"name": "Browning Cynergy", "caliber": "12 Gauge", "price": "$1,300–$2,000", "manufacturer": "Browning", "image": "https://en.wikipedia.org/wiki/File:Browning-Cynergy-Sporting.jpg"},
    ],

    "Side-by-Side": [
        {"name": "CZ Bobwhite", "caliber": "12 Gauge", "price": "$650–$850", "manufacturer": "CZ", "image": ""},
        {"name": "Stoeger Coach Gun", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Stoeger", "image": "https://en.wikipedia.org/wiki/File:Stoeger-Coach-Gun.jpg"},
        {"name": "Ithaca SKB", "caliber": "12 Gauge", "price": "$900–$1,300", "manufacturer": "Ithaca", "image": ""},
        {"name": "Pedersoli Hammer", "caliber": "12 Gauge", "price": "$1,200–$1,800", "manufacturer": "Pedersoli", "image": ""},
        {"name": "Baikal MP-43", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Baikal", "image": ""},
    ],

    "Single-Shot": [
        {"name": "Henry Single Shot", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Henry", "image": ""},
        {"name": "H&R Topper", "caliber": "12 Gauge", "price": "$250–$400", "manufacturer": "H&R", "image": ""},
        {"name": "CVA Scout", "caliber": "12 Gauge", "price": "$350–$550", "manufacturer": "CVA", "image": ""},
        {"name": "New England Firearms Pardner", "caliber": "12 Gauge", "price": "$250–$400", "manufacturer": "NEF", "image": ""},
        {"name": "Chiappa Double Badger", "caliber": "12 Gauge", "price": "$450–$650", "manufacturer": "Chiappa", "image": ""},
    ]
}

