# catalog.py

PISTOLS = {
    "Semi-Auto": [
        {"name": "Glock 17", "caliber": "9×19mm", "price": "$500–$650", "manufacturer": "Glock", "image": "https://en.wikipedia.org/wiki/File:Glock_17_(6825676904)_%D0%B1%D0%B5%D0%B7_%D1%84%D0%BE%D0%BD%D0%B0.jpg"},
        {"name": "Glock 19", "caliber": "9×19mm", "price": "$500–$650", "manufacturer": "Glock", "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Glock_19_%289mm%29%2C_Generation_3.jpg/250px-Glock_19_%289mm%29%2C_Generation_3.jpg"},
        {"name": "Glock 26", "caliber": "9×19mm", "price": "$500–$650", "manufacturer": "Glock", "image": "https://en.wikipedia.org/wiki/File:Glock_26_(6971790359).jpg"},
        {"name": "Glock 34", "caliber": "9×19mm", "price": "$600–$750", "manufacturer": "Glock", "image": ""},
        {"name": "Glock 43", "caliber": "9×19mm", "price": "$450–$600", "manufacturer": "Glock", "image": ""},
        {"name": "Glock 21", "caliber": ".45 ACP", "price": "$550–$700", "manufacturer": "Glock", "image": ""},
        {"name": "SIG Sauer P320", "caliber": "9mm", "price": "$500–$700", "manufacturer": "SIG Sauer", "image": "https://en.wikipedia.org/wiki/File:Sig_Sauer_P320_Modular_Handgun_System.jpg"},
        {"name": "SIG Sauer P365", "caliber": "9mm", "price": "$500–$650", "manufacturer": "SIG Sauer", "image": "https://en.wikipedia.org/wiki/File:SIG_Sauer_P365_left_side.jpg"},
        {"name": "SIG Sauer P226", "caliber": "9mm", "price": "$700–$900", "manufacturer": "SIG Sauer", "image": "https://en.wikipedia.org/wiki/File:SIG_Sauer_P226_neu.jpg"},
        {"name": "SIG Sauer P229", "caliber": "9mm", "price": "$700–$900", "manufacturer": "SIG Sauer", "image": ""},
        {"name": "Smith & Wesson M&P 9", "caliber": "9mm", "price": "$450–$600", "manufacturer": "Smith & Wesson", "image": ""},
        {"name": "Smith & Wesson Shield", "caliber": "9mm", "price": "$400–$550", "manufacturer": "Smith & Wesson", "image": ""},
        {"name": "Beretta 92FS", "caliber": "9mm", "price": "$600–$750", "manufacturer": "Beretta", "image": "https://en.wikipedia.org/wiki/File:Beretta-92FS.jpg"},
        {"name": "Beretta APX", "caliber": "9mm", "price": "$450–$600", "manufacturer": "Beretta", "image": ""},
        {"name": "Beretta PX4 Storm", "caliber": "9mm", "price": "$450–$600", "manufacturer": "Beretta", "image": "https://en.wikipedia.org/wiki/File:BerettaPX4Storm.jpg"},
        {"name": "CZ 75", "caliber": "9mm", "price": "$600–$800", "manufacturer": "CZ", "image": ""},
        {"name": "CZ P-10 C", "caliber": "9mm", "price": "$450–$600", "manufacturer": "CZ", "image": ""},
        {"name": "CZ Shadow 2", "caliber": "9mm", "price": "$1,100–$1,600", "manufacturer": "CZ", "image": ""},
        {"name": "Ruger SR9", "caliber": "9mm", "price": "$400–$550", "manufacturer": "Ruger", "image": ""},
        {"name": "Ruger Security-9", "caliber": "9mm", "price": "$350–$500", "manufacturer": "Ruger", "image": ""},
        {"name": "Ruger LCP", "caliber": ".380 ACP", "price": "$300–$450", "manufacturer": "Ruger", "image": ""},
        {"name": "Colt 1911", "caliber": ".45 ACP", "price": "$800–$1,200", "manufacturer": "Colt", "image": ""},
        {"name": "Kimber 1911", "caliber": ".45 ACP", "price": "$900–$1,400", "manufacturer": "Kimber", "image": ""},
        {"name": "Springfield XD", "caliber": "9mm", "price": "$450–$600", "manufacturer": "Springfield Armory", "image": ""},
        {"name": "Springfield Hellcat", "caliber": "9mm", "price": "$500–$650", "manufacturer": "Springfield Armory", "image": ""},
        {"name": "FN 509", "caliber": "9mm", "price": "$600–$750", "manufacturer": "FN", "image": ""},
        {"name": "FN FNX-45", "caliber": ".45 ACP", "price": "$700–$900", "manufacturer": "FN", "image": ""},
        {"name": "Walther PPQ", "caliber": "9mm", "price": "$500–$650", "manufacturer": "Walther", "image": ""},
        {"name": "Walther PDP", "caliber": "9mm", "price": "$550–$700", "manufacturer": "Walther", "image": ""},
        {"name": "Walther PPK", "caliber": ".380 ACP", "price": "$600–$850", "manufacturer": "Walther", "image": ""},
        {"name": "Taurus G2C", "caliber": "9mm", "price": "$250–$350", "manufacturer": "Taurus", "image": ""},
        {"name": "Taurus PT92", "caliber": "9mm", "price": "$400–$550", "manufacturer": "Taurus", "image": ""},
        {"name": "Canik TP9SF", "caliber": "9mm", "price": "$350–$500", "manufacturer": "Canik", "image": ""},
        {"name": "Canik Mete SFx", "caliber": "9mm", "price": "$500–$650", "manufacturer": "Canik", "image": ""},
    ],

    "Automatic": [
        {"name": "Glock 18", "caliber": "9×19mm", "price": "Restricted", "manufacturer": "Glock", "image": ""},
        {"name": "Glock 18C", "caliber": "9×19mm", "price": "Restricted", "manufacturer": "Glock", "image": ""},
        {"name": "Beretta 93R", "caliber": "9×19mm", "price": "Restricted", "manufacturer": "Beretta", "image": ""},
        {"name": "Stechkin APS", "caliber": "9×18mm", "price": "Restricted", "manufacturer": "Tula Arsenal", "image": ""},
        {"name": "CZ 75 Automatic", "caliber": "9×19mm", "price": "Restricted", "manufacturer": "CZ", "image": ""},
    ],

    "Revolver": [
        {"name": "Smith & Wesson Model 686", "caliber": ".357 Magnum", "price": "$700–$900", "manufacturer": "Smith & Wesson", "image": ""},
        {"name": "Smith & Wesson Model 29", "caliber": ".44 Magnum", "price": "$900–$1,200", "manufacturer": "Smith & Wesson", "image": ""},
        {"name": "Smith & Wesson Model 642", "caliber": ".38 Special", "price": "$400–$600", "manufacturer": "Smith & Wesson", "image": ""},
        {"name": "Colt Python", "caliber": ".357 Magnum", "price": "$1,200–$1,800", "manufacturer": "Colt", "image": ""},
        {"name": "Ruger GP100", "caliber": ".357 Magnum", "price": "$650–$850", "manufacturer": "Ruger", "image": ""},
        {"name": "Ruger Redhawk", "caliber": ".44 Magnum", "price": "$800–$1,100", "manufacturer": "Ruger", "image": ""},
        {"name": "Taurus Judge", "caliber": ".410 / .45 Colt", "price": "$450–$650", "manufacturer": "Taurus", "image": ""},
        {"name": "Taurus Tracker", "caliber": ".357 Magnum", "price": "$400–$600", "manufacturer": "Taurus", "image": ""},
        {"name": "Colt King Cobra", "caliber": ".357 Magnum", "price": "$900–$1,200", "manufacturer": "Colt", "image": ""},
        {"name": "Ruger SP101", "caliber": ".357 Magnum", "price": "$600–$800", "manufacturer": "Ruger", "image": ""},
        {"name": "Smith & Wesson Model 60", "caliber": ".357 Magnum", "price": "$650–$850", "manufacturer": "Smith & Wesson", "image": ""},
        {"name": "Smith & Wesson Model 19", "caliber": ".357 Magnum", "price": "$750–$950", "manufacturer": "Smith & Wesson", "image": ""},
        {"name": "Charter Arms Bulldog", "caliber": ".44 Special", "price": "$400–$550", "manufacturer": "Charter Arms", "image": ""},
        {"name": "Ruger LCR", "caliber": ".38 Special", "price": "$450–$600", "manufacturer": "Ruger", "image": ""},
        {"name": "Colt Anaconda", "caliber": ".44 Magnum", "price": "$1,300–$1,700", "manufacturer": "Colt", "image": ""},
    ]
}

RIFLES = {
    "Semi-Auto": [
        {"name": "AR-15", "caliber": "5.56×45mm", "price": "$500–$1,000", "manufacturer": "Various", "image": ""},
        {"name": "AR-10", "caliber": ".308 Win", "price": "$900–$1,500", "manufacturer": "Various", "image": ""},
        {"name": "PSA AR-15", "caliber": "5.56×45mm", "price": "$450–$750", "manufacturer": "PSA", "image": ""},
        {"name": "Colt AR15", "caliber": "5.56×45mm", "price": "$900–$1,300", "manufacturer": "Colt", "image": ""},
        {"name": "Daniel Defense DDM4", "caliber": "5.56×45mm", "price": "$1,400–$2,000", "manufacturer": "Daniel Defense", "image": ""},
        {"name": "SIG Sauer MCX", "caliber": "5.56×45mm", "price": "$1,600–$2,500", "manufacturer": "SIG Sauer", "image": ""},
        {"name": "FN SCAR 16", "caliber": "5.56×45mm", "price": "$2,500–$3,200", "manufacturer": "FN", "image": ""},
        {"name": "AK-47", "caliber": "7.62×39mm", "price": "$600–$1,200", "manufacturer": "Various", "image": ""},
        {"name": "AK-74", "caliber": "5.45×39mm", "price": "$700–$1,300", "manufacturer": "Various", "image": ""},
        {"name": "Zastava ZPAP M70", "caliber": "7.62×39mm", "price": "$900–$1,300", "manufacturer": "Zastava", "image": ""},
        {"name": "WASR-10", "caliber": "7.62×39mm", "price": "$700–$1,000", "manufacturer": "Century Arms", "image": ""},
        {"name": "Ruger Mini-14", "caliber": "5.56×45mm", "price": "$900–$1,200", "manufacturer": "Ruger", "image": ""},
        {"name": "Ruger 10/22", "caliber": ".22 LR", "price": "$250–$400", "manufacturer": "Ruger", "image": ""},
        {"name": "Springfield M1A", "caliber": ".308 Win", "price": "$1,400–$2,000", "manufacturer": "Springfield Armory", "image": ""},
        {"name": "IWI Tavor X95", "caliber": "5.56×45mm", "price": "$1,500–$2,000", "manufacturer": "IWI", "image": ""},
        {"name": "Steyr AUG", "caliber": "5.56×45mm", "price": "$1,800–$2,300", "manufacturer": "Steyr", "image": ""},
        {"name": "FN PS90", "caliber": "5.7×28mm", "price": "$1,500–$1,900", "manufacturer": "FN", "image": ""},
        {"name": "Kel-Tec SUB-2000", "caliber": "9mm", "price": "$450–$650", "manufacturer": "Kel-Tec", "image": ""},
        {"name": "Kel-Tec RDB", "caliber": "5.56×45mm", "price": "$900–$1,200", "manufacturer": "Kel-Tec", "image": ""},
        {"name": "Hi-Point 995TS", "caliber": "9mm", "price": "$300–$450", "manufacturer": "Hi-Point", "image": ""},
    ],

    "Automatic": [
        {"name": "M16A4", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "Colt", "image": ""},
        {"name": "M4 Carbine", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "Colt", "image": ""},
        {"name": "AKM", "caliber": "7.62×39mm", "price": "Restricted", "manufacturer": "Kalashnikov Concern", "image": ""},
        {"name": "AK-74M", "caliber": "5.45×39mm", "price": "Restricted", "manufacturer": "Kalashnikov Concern", "image": ""},
        {"name": "HK416", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "Heckler & Koch", "image": ""},
        {"name": "SIG SG 550", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "SIG", "image": ""},
        {"name": "FAMAS F1", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "GIAT", "image": ""},
        {"name": "Steyr AUG A1 (Auto)", "caliber": "5.56×45mm", "price": "Restricted", "manufacturer": "Steyr", "image": ""},
    ],

    "Bolt-Action": [
        {"name": "Remington 700", "caliber": ".308 Win", "price": "$600–$900", "manufacturer": "Remington", "image": ""},
        {"name": "Savage 110", "caliber": ".308 Win", "price": "$600–$900", "manufacturer": "Savage", "image": ""},
        {"name": "Savage Axis", "caliber": ".308 Win", "price": "$350–$550", "manufacturer": "Savage", "image": ""},
        {"name": "Ruger American", "caliber": ".308 Win", "price": "$400–$650", "manufacturer": "Ruger", "image": ""},
        {"name": "Ruger Precision Rifle", "caliber": ".308 Win", "price": "$1,300–$1,800", "manufacturer": "Ruger", "image": ""},
        {"name": "Tikka T3x", "caliber": ".308 Win", "price": "$700–$1,000", "manufacturer": "Tikka", "image": ""},
        {"name": "Bergara B-14", "caliber": ".308 Win", "price": "$700–$1,000", "manufacturer": "Bergara", "image": ""},
        {"name": "Howa 1500", "caliber": ".308 Win", "price": "$500–$750", "manufacturer": "Howa", "image": ""},
        {"name": "Weatherby Vanguard", "caliber": ".308 Win", "price": "$550–$800", "manufacturer": "Weatherby", "image": ""},
        {"name": "Winchester Model 70", "caliber": ".30-06", "price": "$800–$1,300", "manufacturer": "Winchester", "image": ""},
        {"name": "Winchester XPR", "caliber": ".308 Win", "price": "$450–$650", "manufacturer": "Winchester", "image": ""},
        {"name": "Christensen Arms Mesa", "caliber": ".308 Win", "price": "$1,200–$1,700", "manufacturer": "Christensen Arms", "image": ""},
        {"name": "Mossberg Patriot", "caliber": ".308 Win", "price": "$400–$600", "manufacturer": "Mossberg", "image": ""},
        {"name": "CZ 457", "caliber": ".22 LR", "price": "$450–$700", "manufacturer": "CZ", "image": ""},
        {"name": "Barrett MRAD", "caliber": ".308 Win", "price": "$4,000–$6,000", "manufacturer": "Barrett", "image": ""},
        {"name": "Browning X-Bolt", "caliber": ".308 Win", "price": "$700–$1,200", "manufacturer": "Browning", "image": ""},
        {"name": "Savage 12 FV", "caliber": ".308 Win", "price": "$600–$900", "manufacturer": "Savage", "image": ""},
        {"name": "Ruger Hawkeye", "caliber": ".308 Win", "price": "$700–$1,000", "manufacturer": "Ruger", "image": ""},
        {"name": "T/C Compass", "caliber": ".308 Win", "price": "$350–$500", "manufacturer": "Thompson/Center", "image": ""},
        {"name": "Bergara Premier", "caliber": ".308 Win", "price": "$2,000–$3,000", "manufacturer": "Bergara", "image": ""},
    ],

    "Lever-Action": [
        {"name": "Marlin 336", "caliber": ".30-30", "price": "$600–$900", "manufacturer": "Marlin", "image": ""},
        {"name": "Marlin 1895", "caliber": ".45-70 Gov", "price": "$900–$1,300", "manufacturer": "Marlin", "image": ""},
        {"name": "Henry Big Boy", "caliber": ".357 Magnum", "price": "$700–$1,000", "manufacturer": "Henry", "image": ""},
        {"name": "Henry Long Ranger", "caliber": ".308 Win", "price": "$900–$1,200", "manufacturer": "Henry", "image": ""},
        {"name": "Henry Golden Boy", "caliber": ".22 LR", "price": "$500–$750", "manufacturer": "Henry", "image": ""},
        {"name": "Winchester 1894", "caliber": ".30-30", "price": "$800–$1,200", "manufacturer": "Winchester", "image": ""},
        {"name": "Rossi R92", "caliber": ".357 Magnum", "price": "$550–$750", "manufacturer": "Rossi", "image": ""},
        {"name": "Browning BLR", "caliber": ".308 Win", "price": "$800–$1,200", "manufacturer": "Browning", "image": ""},
        {"name": "Marlin 39A", "caliber": ".22 LR", "price": "$700–$1,000", "manufacturer": "Marlin", "image": ""},
        {"name": "Henry Side Gate", "caliber": ".45-70 Gov", "price": "$900–$1,300", "manufacturer": "Henry", "image": ""},
    ],
}


SHOTGUNS = {
    "Pump-Action": [
        {"name": "Remington 870", "caliber": "12 Gauge", "price": "$350–$500", "manufacturer": "Remington", "image": ""},
        {"name": "Mossberg 500", "caliber": "12 Gauge", "price": "$300–$450", "manufacturer": "Mossberg", "image": ""},
        {"name": "Mossberg 590", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Mossberg", "image": ""},
        {"name": "Mossberg Maverick 88", "caliber": "12 Gauge", "price": "$250–$350", "manufacturer": "Mossberg", "image": ""},
        {"name": "Winchester SXP", "caliber": "12 Gauge", "price": "$300–$450", "manufacturer": "Winchester", "image": ""},
        {"name": "Benelli Nova", "caliber": "12 Gauge", "price": "$400–$550", "manufacturer": "Benelli", "image": ""},
        {"name": "Benelli SuperNova", "caliber": "12 Gauge", "price": "$450–$600", "manufacturer": "Benelli", "image": ""},
        {"name": "Stevens 320", "caliber": "12 Gauge", "price": "$250–$350", "manufacturer": "Stevens", "image": ""},
        {"name": "Browning BPS", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Browning", "image": ""},
        {"name": "Kel-Tec KSG", "caliber": "12 Gauge", "price": "$700–$900", "manufacturer": "Kel-Tec", "image": ""},
        {"name": "TriStar Cobra", "caliber": "12 Gauge", "price": "$200–$300", "manufacturer": "TriStar", "image": ""},
        {"name": "Mossberg 835 Ulti-Mag", "caliber": "12 Gauge", "price": "$350–$500", "manufacturer": "Mossberg", "image": ""},
        {"name": "Winchester Model 12", "caliber": "12 Gauge", "price": "$600–$1,000", "manufacturer": "Winchester", "image": ""},
        {"name": "H&R Pardner Pump", "caliber": "12 Gauge", "price": "$250–$350", "manufacturer": "H&R", "image": ""},
        {"name": "Ithaca 37", "caliber": "12 Gauge", "price": "$600–$900", "manufacturer": "Ithaca", "image": ""},
    ],

    "Semi-Auto": [
        {"name": "Remington 1100", "caliber": "12 Gauge", "price": "$600–$900", "manufacturer": "Remington", "image": ""},
        {"name": "Remington 1187", "caliber": "12 Gauge", "price": "$650–$950", "manufacturer": "Remington", "image": ""},
        {"name": "Mossberg 930", "caliber": "12 Gauge", "price": "$450–$650", "manufacturer": "Mossberg", "image": ""},
        {"name": "Mossberg 940 Pro", "caliber": "12 Gauge", "price": "$900–$1,200", "manufacturer": "Mossberg", "image": ""},
        {"name": "Benelli M2", "caliber": "12 Gauge", "price": "$1,100–$1,500", "manufacturer": "Benelli", "image": ""},
        {"name": "Benelli M4", "caliber": "12 Gauge", "price": "$1,800–$2,200", "manufacturer": "Benelli", "image": ""},
        {"name": "Benelli Montefeltro", "caliber": "12 Gauge", "price": "$900–$1,200", "manufacturer": "Benelli", "image": ""},
        {"name": "Benelli Ethos", "caliber": "12 Gauge", "price": "$1,500–$2,000", "manufacturer": "Benelli", "image": ""},
        {"name": "Beretta A300", "caliber": "12 Gauge", "price": "$600–$800", "manufacturer": "Beretta", "image": ""},
        {"name": "Beretta 1301", "caliber": "12 Gauge", "price": "$1,000–$1,400", "manufacturer": "Beretta", "image": ""},
        {"name": "Beretta A400", "caliber": "12 Gauge", "price": "$1,300–$1,800", "manufacturer": "Beretta", "image": ""},
        {"name": "Browning A5", "caliber": "12 Gauge", "price": "$1,200–$1,800", "manufacturer": "Browning", "image": ""},
        {"name": "Browning Maxus", "caliber": "12 Gauge", "price": "$900–$1,200", "manufacturer": "Browning", "image": ""},
        {"name": "Stoeger M3000", "caliber": "12 Gauge", "price": "$350–$500", "manufacturer": "Stoeger", "image": ""},
        {"name": "Weatherby Element", "caliber": "12 Gauge", "price": "$350–$550", "manufacturer": "Weatherby", "image": ""},
    ],

    "Over/Under": [
        {"name": "CZ Drake", "caliber": "12 Gauge", "price": "$600–$800", "manufacturer": "CZ", "image": ""},
        {"name": "CZ Redhead", "caliber": "12 Gauge", "price": "$700–$900", "manufacturer": "CZ", "image": ""},
        {"name": "Browning Citori", "caliber": "12 Gauge", "price": "$1,500–$2,500", "manufacturer": "Browning", "image": ""},
        {"name": "Winchester 101", "caliber": "12 Gauge", "price": "$1,200–$1,800", "manufacturer": "Winchester", "image": ""},
        {"name": "Stoeger Condor", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Stoeger", "image": ""},
        {"name": "Mossberg Silver Reserve", "caliber": "12 Gauge", "price": "$500–$700", "manufacturer": "Mossberg", "image": ""},
        {"name": "Stevens 555", "caliber": "12 Gauge", "price": "$450–$650", "manufacturer": "Stevens", "image": ""},
        {"name": "Franchi Instinct", "caliber": "12 Gauge", "price": "$600–$850", "manufacturer": "Franchi", "image": ""},
        {"name": "Weatherby Orion", "caliber": "12 Gauge", "price": "$650–$900", "manufacturer": "Weatherby", "image": ""},
        {"name": "Browning Cynergy", "caliber": "12 Gauge", "price": "$1,300–$2,000", "manufacturer": "Browning", "image": ""},
    ],

    "Side-by-Side": [
        {"name": "CZ Bobwhite", "caliber": "12 Gauge", "price": "$650–$850", "manufacturer": "CZ", "image": ""},
        {"name": "Stoeger Coach Gun", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Stoeger", "image": ""},
        {"name": "Ithaca SKB", "caliber": "12 Gauge", "price": "$900–$1,300", "manufacturer": "Ithaca", "image": ""},
        {"name": "Pedersoli Hammer", "caliber": "12 Gauge", "price": "$1,200–$1,800", "manufacturer": "Pedersoli", "image": ""},
        {"name": "Baikal MP-43", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Baikal", "image": ""},
    ],

    "Single-Shot": [
        {"name": "Henry Single Shot", "caliber": "12 Gauge", "price": "$400–$600", "manufacturer": "Henry", "image": ""},
        {"name": "H&R Topper", "caliber": "12 Gauge", "price": "$250–$400", "manufacturer": "H&R", "image": ""},
        {"name": "CVA Scout", "caliber": "12 Gauge", "price": "$350–$550", "manufacturer": "CVA", "image": ""},
        {"name": "New England Firearms Pardner", "caliber": "12 Gauge", "price": "$250–$400", "manufacturer": "NEF", "image": ""},
        {"name": "Chiappa Double Badger", "caliber": "12 Gauge", "price": "$450–$650", "manufacturer": "Chiappa", "image": ""},
    ]
}

